# SPDX-FileCopyrightText: © 2025 Kyurenpoto <heal9179@gmail.com>
#
# SPDX-License-Identifier: MIT

---
name: macos-ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - release/*
  pull_request:
    branches:
      - main
      - dev
      - release/*

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        preset: [macos-debug, macos-release]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install cmake & ninja
        uses: lukka/get-cmake@latest
        with:
          cmake-version: latest

      - name: install python
        run: |
          brew install llvm clang-format python pipx

      - name: install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh
          echo "VCPKG_ROOT=$(pwd)" >> $GITHUB_ENV
          cd ..
        id: vcpkg

      - name: install conan
        run: |
          pipx install conan
        id: conan

      - name: install clang
        run: |
          brew install llvm@16
          echo 'export PATH="/opt/homebrew/opt/llvm@16/bin:$PATH"' >> $GITHUB_ENV
          # sudo ln -sf /usr/homebrew/opt/llvm@16/bin/clang /usr/homebrew/bin/clang
          # sudo ln -sf /usr/homebrew/opt/llvm@16/bin/clang++ /usr/homebrew/bin/clang++
          clang --version

      - name: configure
        run: |
          cmake --preset ${{ matrix.preset }}

      - name: build
        run: cmake --build --preset ${{ matrix.preset }} -j4 --verbose

      - name: test
        run: |
          ctest --preset ${{ matrix.preset }} -j4 --verbose --output-on-failure
