# SPDX-FileCopyrightText: © 2025 Kyurenpoto <heal9179@gmail.com>
#
# SPDX-License-Identifier: MIT

---
name: dev/stage test result

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

permissions:
  contents: write
  issues: write

jobs:
  parse-issue-ids:
    runs-on: ubuntu-latest
    if: ${{
      (
        github.event.workflow_run.head_branch == 'dev' || 
        startsWith(github.event.workflow_run.head_branch, 'release/') || 
        startsWith(github.event.workflow_run.head_branch, 'non-release/')
      ) && 
      github.event.workflow_run.head_ref == ''
    }}
    steps:
      - name: target environment
        run: |
          if [ "${{ github.event.workflow_run.head_branch }}" == "dev" ]; then
            echo "env=dev" >> $GITHUB_ENV
          else
            echo "env=staging" >> $GITHUB_ENV
          fi

      - name: set comment message
        id: set_message
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" == "success" ]; then
            echo "message=✅ ${{ env.env }} test completed successfully!" >> $GITHUB_OUTPUT
          else
            echo "message=❌ ${{ env.env }} test failed. Please check the details at: https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}" >> $GITHUB_OUTPUT
          fi

      - name: extract issue numbers from commit message
        id: extract_issues
        run: |
          ISSUE_NUMBERS=$(echo "${{ github.event.workflow_run.head_commit.message }}" | grep -o '#[0-9]\+' | tr -d '#' | sort -u)
          JSON_ARRAY=$(echo "$ISSUE_NUMBERS" | jq -R . | jq -s .)
          echo "issue_numbers=$JSON_ARRAY" >> $GITHUB_OUTPUT

      - name: post comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ env.ISSUE_NUMBER }}
          body: ${{ env.message }}

    outputs:
      issue_numbers: ${{ steps.extract_issues.outputs.issue_numbers }}
      message: ${{ steps.set_message.outputs.message }}
